### ISSUE TITLE
[Bug]: back button doesn't match browser behavior

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/gfsc-v3#105]
## Description
on individual projects the "go back" doesn't take you back to where you were, ie `/our-work/consultancy-research/` it just leads to `our-work`

## Steps to reproduce
1. visit the homepage
1. click our work at the top
2. select 'browse' under Consultancy and Research
3. click a project, say 'A Growing Threat to Life' report
4. scroll down and hit the "back" button

## Platform (if relevant)
What device and browser were you using?

**Comment by r-ferrier** [comment]
No longer relevant
