### ISSUE TITLE
[Bug]: themes for projects lack content

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/gfsc-v3#109]
## Description
- I clicked on a theme expecting to find similar projects but got a theme definition.

## Steps to reproduce
1. visit https://gfsc.pages.dev/project/mossleyheritage/
1. and click through to "local history" https://gfsc.pages.dev/our-work/theme/localhistory/

list of themes on site

```
anti-racism
digital-autonomy
environment
hulme-and-manchester
local-history
mutual-aid
trans-lib
trans-liberation
```
available pages for themes

```
content/our-work/theme
├── antiracism.md
├── digitalautonomy.md
├── disabilityactivism.md
├── environment.md
├── hulmeandmanchester.md
├── _index.md
├── localhistory.md
├── mutualaid.md
└── transliberation.md
```

**Comment by r-ferrier** [comment]
no longer relevant
