### ISSUE TITLE
[Bug]: aditional space introduced by rawHtml shortcode

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/gfsc-v3#113]
## Description

unintentended white space introduced by  ` rawHtml` shortcode

https://gfsc.pages.dev/blog/2019/placecal-capabilities-approach/

```md
an ongoing negotiation between all Beings{{<rawhtml>}}<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>{{</rawhtml>}}.
```

visible before and after footnotes and elsewhere
![Screenshot 2022-11-16 at 17-31-33 Making a place for technology in communities](https://user-images.githubusercontent.com/6824891/202251873-160577f0-e08c-46d5-bae6-dab18c855acc.png)

**Comment by r-ferrier** [comment]
This is an inconsistent problem and is fixed by using a different convention of adding footnotes like this:

```
Reference in text[^footnote_identifier]

---

[^footnote_identifier]: [**Author (year)**. Title, Location: Publisher.](link)
```

Not sure if it's worth my time to go back and edit this page - it's just one blog post from 2019 that looks like this from what I can see!

**Comment by kimadactyl** [comment]
this is also an out of date draft of the article - i think simplest solution is to link to the journal page

https://www.tandfonline.com/doi/full/10.1080/1369118X.2020.1767173

(there may be other tickets about this too)
