### ISSUE TITLE
Show relevant blog posts on project pages

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/gfsc-v3#173]
> It would be cool if the project pages showed teasers of blog posts relating to them

## acceptance criteria

- [ ] blogposts can be tagged with an associated project
- [ ] titles of related blogposts shown on portfolio page
- [ ] titles link to blog post

## questions

- summary?
- image?
- placement on page?
- design?

### step one

- create an unstyled partial that generates a list of blog post links given a project tag.
- answer above questions and work out a wireframe

**Comment by kimadactyl** [comment]
@undividual - i think this was my idea for how to do fuller project pages, basically just let them have approparitely tagged blogs underneath. but this may be mixing 2 things together that are just a bit differnet

**Comment by kimadactyl** [comment]
Not closing as @aaaaargZombies is assigned but i think this is a dupe of above ticket

**Comment by aaaaargZombies** [comment]
closed by #361
