### ISSUE TITLE
Add a "last modified" date to blog posts and portfolio

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/gfsc-v3#178]
I think this is really useful and relevant info esp if we are going to try and keep on top of them

Looks like it's doable with Git

https://mertbakir.gitlab.io/hugo/last-modified-date-in-hugo/

**Comment by ivan-kocienski-gfsc** [comment]
This is a duplicate of https://github.com/geeksforsocialchange/gfsc-v3/issues/74

**Comment by kimadactyl** [comment]
A semi dupe, but this one mentions portfolio too.
