### ISSUE TITLE
[Bug]: Privacy policy missing

### ISSUE THREAD

**Issue by studiosquid** [geeksforsocialchange/gfsc-v3#182]
## Acceptance criteria

- [x] #249
- [ ] #250
- [ ] #251

## Description
The privacy policy in the footer is not linked to a page, unsure if this is because you've worked carefully to ensure there's nothing you need to declare (I was of the view legally you have to have one but not 100% sure that's true!) or it's just been forgotten.

I'd suggest it's hidden temporarily for launch or it be linked up :)

**Comment by r-ferrier** [comment]
closing this as it is sharded out into other tasks
