### ISSUE TITLE
Publish properly formed RSS feed

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/gfsc-v3#216]
## User story
As an enjoyer of blogs I need to be able to find the RSS feed link so that I can get updated when new posts are made without relying on social media announcements and algorithm roulette.

## Acceptance criteria

- [ ] RSS feed is properly sorted
- [ ] RSS feed shows fulltext
- [ ] RSS feed shows only blog posts and new portfolio stuff?
- [ ] Add RSS link to socials bit in footer 

## Implementation notes & questions

- http://gfsc.studio/index.xml
- this is hugos default, do we want to modify it at all?
- is the socials link the best place?

**Comment by aaaaargZombies** [comment]
![Screenshot_20230221-093400](https://user-images.githubusercontent.com/6824891/220306410-c6ec4879-684e-4fb5-ba43-f77c5bab58b6.png)

They are displaying in order in my RSS reader

**Comment by kimadactyl** [comment]
oh nice ok i guess yeah it doesn't matter what order they're published in?

maybe let's just add publication dates to the projects? i don't really think we should have e.g. staff pages in there tho.

how hard is this to modify?

**Comment by aaaaargZombies** [comment]
ok rss template was pretty easy to modify so the projects need dates adding and then we can make the link discoverable
