### ISSUE TITLE
Add TSN to website portfolio

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/gfsc-v3#218]
[Trans Safety Network.zip](https://github.com/geeksforsocialchange/gfsc-v3/files/10863533/Trans.Safety.Network.zip)

**Comment by honor-gfsc** [comment]
Have drafted and opened PR with draft version of project page. Copy needs approval from someone who worked directly on the project/has more contextual information than me to ensure it's all correct.
