### ISSUE TITLE
Footnotes aren't styled

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/gfsc-v3#229]
## User story

As a writer I need to be able to add footnotes and have them feel more connected to the article

- fontsize is too small
- combination of donate box, new section, logo `hr` creates a lot of physical distance from the article and footnotes

![image](https://github.com/geeksforsocialchange/gfsc-v3/assets/6824891/939eeec4-d031-41a0-9ce8-d5265f6b729e)

https://gfsc.studio/blog/2022/why-is-it-so-hard-to-do-nice-things/

## Acceptance criteria 

- [ ] increase fontsize to be equal to body text
- [ ] remove logo from footer

## Implementation notes & questions

honor has created this alternative/recommendation by writing the footnote into the article

https://github.com/geeksforsocialchange/gfsc-v3/blob/main/content/blog/2023/raftt-design-blog-2/index.md?plain=1#L128-L132

<img width="1014" alt="Screenshot 2023-04-17 at 15 42 30" src="https://user-images.githubusercontent.com/127757676/232525248-32d64af0-8807-4b52-809d-703d4033179f.png">

## Implementation plan

- requires agreement on design to generate acceptance criteria from

**Comment by kimadactyl** [comment]
on mobile too - this is deffo new, it did not used to look like this!

![Uploading signal-2023-04-18-175207_002.jpeg…]()
