### ISSUE TITLE
[Bug]: Sign up (to newsletter?) triggers an email with a link to survey described as 2021

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/gfsc-v3#234]
## Description
Reported in discord:
![image](https://github.com/geeksforsocialchange/gfsc-v3/assets/861172/cad4bcbd-2dab-4a97-91b5-d5cfda655567)

## Steps to reproduce
1. Need to verify - but I think... sign up for our newsletter? And get an email...

## Platform (if relevant)
What device and browser were you using?

**Comment by kimadactyl** [comment]
Ahha this was in the email title - fixed now

<img width="1016" alt="Screenshot 2023-06-14 at 14 37 01" src="https://github.com/geeksforsocialchange/gfsc-v3/assets/511734/db9ca9c9-4bdb-4279-84d9-b1705c5be410">

<img width="1365" alt="Screenshot 2023-06-14 at 14 37 19" src="https://github.com/geeksforsocialchange/gfsc-v3/assets/511734/e95d621a-8637-4931-9fb1-d5ff28ab02fd">
