### ISSUE TITLE
[Bug]: Links in podcast descriptions are broken

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/gfsc-v3#240]
## Description

Our podcast out in the wild has shorturls like this: 

https://gfsc.studio/podcast/1

These are now broken

- Can we investigate the ability to add in some redirects so visitors to https://gfsc.studio/podcast/1 or https://gfsc.studio/podcast/2 see the correct podcast?

## Steps to reproduce

1. Look up GFSC Podcast on Spotify
2. Try and follow the episode link
3. It goes to the homepage

## Platform (if relevant)

What device and browser were you using?

**Comment by ivan-kocienski-gfsc** [comment]
So I did some reading

https://discourse.gohugo.io/t/url-redirect-forwarding/4689/19
https://harrycresswell.com/writing/hugo-netlify-redirects/

And it seems there are a few ways to do this
- `<meta>` redirects
- Some kind of netlify redirect
- Webserver redirects
- Another configuration some place?

**Comment by ivan-kocienski-gfsc** [comment]
I am going to investigate the meta redirect first

**Comment by ivan-kocienski-gfsc** [comment]
Turns out there's an `alias` header option in a given blog post that will redirect from that URL to the correct blog

https://gohugo.io/content-management/urls/#aliases
