### ISSUE TITLE
Add themes to the website

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/gfsc-v3#263]
These all need fully fleshing out and should be worked on in this order - especially the first three, none of which can be merged before the one before each is merged!

See figma diagram below and reuse code from old PRs in the repo wherever possible

- [x] #264
- [x] #265
- [x] #266
- [x] #267
- [x] #268

https://www.figma.com/file/rLewb9kn4mUt8lLI0wuC7f/GFSC?type=design&node-id=245-314&mode=design&t=fQa9SLXXAEXhPLPT-0

**Comment by aaaaargZombies** [comment]
we did it!
