### ISSUE TITLE
Reinstate homepage themes (find previous commit!)

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/gfsc-v3#265]

**Comment by ivan-kocienski-gfsc** [comment]
Looks like the commit can be found https://github.com/geeksforsocialchange/gfsc-v3/commits/030cace

Specifically https://github.com/geeksforsocialchange/gfsc-v3/commit/030cacec7c5be61e8a51cc0afd748d9b4ff3a67a

**Comment by r-ferrier** [comment]
verified

![Screenshot 2023-07-06 at 11 46 14](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/189d45d0-1ab3-4df3-ba9d-a415550925dc)

![Screenshot 2023-07-06 at 11 45 54](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/77aa4c36-b8d8-42f3-ba89-c1f01837d442)
