### ISSUE TITLE
Add the tags to project cards shown on the theme, category, and our work pages

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/gfsc-v3#267]
## Description

Projects on the work pages should contain a list of tags to show which categories & themes they belong to

(current)

![Screenshot 2023-06-28 at 13 52 15](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/65f17285-0c62-40c8-b5b4-3a6e3db05de4)

(proposed)

![Screenshot 2023-06-28 at 13 51 15](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/a9bc2ca3-a8bb-4855-b753-e683b6a94ceb)

https://www.figma.com/file/rLewb9kn4mUt8lLI0wuC7f/GFSC?type=design&node-id=245-314&mode=design&t=fQa9SLXXAEXhPLPT-0

## Acceptance criteria
- [ ] I can see a list of tags on a project card on the `our work` page
- [ ] I can click on a tag to visit the index page for that tag
- [ ] #268

**Comment by aaaaargZombies** [comment]
A warning that the orange on yellow text doesn't pass contrast checks unless it's 1.2*body text size.

It might be nice to make some little tag boxes using this color scheme

![image](https://github.com/geeksforsocialchange/gfsc-v3/assets/6824891/a97e17ef-c30e-4299-80fb-2568bbb02052)

or use the orange color as a decorator but not on the text, emma talked about adding `#`'s to represent tags

**Comment by r-ferrier** [comment]
@aaaaargZombies argh! I think that sounds sensible? We could give it a go and then run it past Emma for approval. Will hold off on the related card for adding these to the actual project pages until this is done - we can apply the same design elements there. I'll stick a blocked label on it.

**Comment by r-ferrier** [comment]
verified

![Screenshot 2023-07-06 at 11 38 07](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/49cdefdf-efee-4719-8099-da7ba1f06841)
