### ISSUE TITLE
[Bug]: Images are being scaled up past 100%

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/gfsc-v3#276]
## Description

Smaller images on the blog are being blown up and going all pixelly

## Steps to reproduce

1. Go to https://gfsc.studio/blog/2021/technology-isnt-a-magic-wand/

Observe screenshot and source image

<img width="1440" alt="Screenshot 2023-06-30 at 12 56 03" src="https://github.com/geeksforsocialchange/gfsc-v3/assets/511734/f278f1d7-9787-46f6-8a09-1cdee6b0df36">

<img width="1440" alt="Screenshot 2023-06-30 at 12 55 57" src="https://github.com/geeksforsocialchange/gfsc-v3/assets/511734/95059307-d351-4f7a-b6d4-d8f7191ccca4">

## Desired solution

Images don't get scaled past 100% source width

**Comment by r-ferrier** [comment]
verified

![Screenshot 2023-07-06 at 11 43 21](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/382bad37-e76f-4191-a46b-897f1cf1211b)
