### ISSUE TITLE
Set up prettier to run on commit

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/gfsc-v3#281]
## User story

As a develop I like to have consistent formatting so that I can read pull requests more easily.

## Acceptance criteria
- [ ] run prettier on code base
- [ ] set up husky to run prettier on commit
- [ ] set up go template plugin to handle html files

## Implementation notes & questions

https://discourse.gohugo.io/t/formatter-for-go-templates/38403

set up the prettier plugin for go templates, perhaps run it once and let people run it in their editors if they like, maybe set up husky to do it on commit

**Comment by aaaaargZombies** [comment]
also raised #191

**Comment by r-ferrier** [comment]
verified: prettier runs on commit
