### ISSUE TITLE
[Bug]: Image captions are not in the correct markup location

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/gfsc-v3#294]
## Description

On https://gfsc.pages.dev/blog/2021/everything-is-connected/ the captions look like this:

![Screenshot_2023-07-06_09-36-49](https://github.com/geeksforsocialchange/gfsc-v3/assets/109223824/2f4a7d1e-1425-4942-83c2-0870fecfab0f)

Obviously the caption text should be in the caption box.

**Comment by r-ferrier** [comment]
verified 

![Screenshot 2023-07-10 at 10 38 40](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/1da5595c-1f1d-4bda-9b11-3f9e79bf089d)
