### ISSUE TITLE
[Bug]: Our Work: Trans Dimension project themes not displaying

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/gfsc-v3#297]
## Description

On [our-work/theme/transliberation](https://gfsc.studio/our-work/theme/transliberation/) project cards should have a list of themes they are related to shown just below the title of the project. 

However: the Trans Dimension is missing this list (visually) but it does turn up in the correct theme. So something is working on the back end but not showing up properly on the front end.

![Screenshot_2023-07-06_11-28-32](https://github.com/geeksforsocialchange/gfsc-v3/assets/109223824/ea460f4a-f645-4095-a545-c95c6114cf50)

**Comment by r-ferrier** [comment]
verified

![Screenshot 2023-07-10 at 10 41 41](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/b909224b-5a76-4098-8b64-bc0566f4abea)
