### ISSUE TITLE
venn diagram is hidden from screen readers

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/gfsc-v3#307]
potential issue that venn diagram is hidden from screen readers and we have regular text in place which might create a mismatch for people who have some vision and use the screen reader as an aid.

**Comment by r-ferrier** [comment]
I've tried this with a screenreader and I don't think the diagram being hidden is necessarily an issue, but because the screenreader only text is placed after the diagram you have no context for the things its reading out while looking at it, so I might move them up the page.

**Comment by r-ferrier** [comment]
verified 

<img width="1326" alt="Screenshot 2023-07-12 at 11 34 11" src="https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/37518c96-12b2-4584-89ca-eb05bc215108">
