### ISSUE TITLE
missing h1

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/gfsc-v3#308]
## Acceptance criteria

One h1 header exists on:

- [ ] homepage
- [ ] studio
- [ ] our work
- [ ] team
- [ ] support
- [ ] blog
- [ ] project page
- [ ] contact

**Comment by ivan-kocienski-gfsc** [comment]
I think I am going to go through all the pages mentioned in the description here and fix all the easy pages to use the correct H1 tags. But there are a number of pages that don't have H1s in them and this is more of a design (to put them in) and copy (what should be said) problem which I will note in the PR

**Comment by r-ferrier** [comment]
verified on all pages except the blog, linked to new issue

**Comment by r-ferrier** [comment]
verified on all pages except the blog, linked to new issue
