### ISSUE TITLE
link to pdf considered bad practice, can we upload the content to the site as post?

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/gfsc-v3#317]
Links to PDFs are considered bad usability.

Let's keep the existing content as is but moving forward only link to PDFs if absolutely necessary. 

This guideline should form part of a "Accessibility and SEO" document for content writers.

**Comment by kimadactyl** [comment]
> Links to PDFs are considered bad usability.

Hard disagree with this catagorical statement - different things are right for differnet audiences and use cases

Can you elabourate?

**Comment by katjam** [comment]
It's because access to content in pdfs is not as flexible/ customisable as
other formats. As a minimum, where a pdf is provided, it should be
supplimented with content in an alternative format.

On a train but this is good for starters on more context from
https://www.gov.uk/guidance/publishing-accessible-documents

**Comment by honor-gfsc** [comment]
@kimadactyl i think sometimes the content of zines etc can be re-presented in a slightly different way which allows for both webpage and pdf. i think where possible, information which is highly visual/intended to be distributed offline/outside of our website should be presented as both - but this leads us down the path of having cluttered links every time we want to link to something, and maybe too many choices or steps to actually get to the information you want. overall i am pro us having everything in both webpage format and PDF format if the PDF has some utility (more easily shareable, highly visual, etc) 

examples where a zine has been turned into a readable, usable webpage and is presented in both formats: https://cassidy.zone/zines
