### ISSUE TITLE
low contrast text on unordered list, needs to be 4.5:1 or 3:1 with text 1.2* larger than body

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/gfsc-v3#321]
on: project - pube, probably others

## Acceptance criteria

- [ ] `ul` elements have sufficient contrast

## implementation plan

- unordered lists use `$copy` color instead of the bright orange

**Comment by aaaaargZombies** [comment]
![image](https://github.com/geeksforsocialchange/gfsc-v3/assets/6824891/3156e925-a13a-4b5b-8459-0b4bfe91a2ea)
