### ISSUE TITLE
on a screen that has the hamburger menu tab focus has problems, can't see that hamburger is focused, then once open the next tab index is not the menu item. seems to be able to reach them by tabbing down page then back up.

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/gfsc-v3#322]
## Acceptance criteria

- in desktop mode when nav menu is always visible
  - [ ] pressing tab key tabs through the menu options and then on to any content links
- in tablet mode when burger menu is visible
  - [ ] the burger menu link should be outlined when tab focus is on menu
  - [ ] pressing tab again (when menu is hidden) takes you to the next link on the page
  - [ ] pressing `spacebar` when the burger menu button is focused toggles the nav menu
  - [ ] when the nav menu is shown user can tab through the menu (and then on to the rest of the page)
  - [ ] Behaviour should default to behaviour after tabbing down & up

https://github.com/geeksforsocialchange/gfsc-v3/assets/6824891/2ec835fe-5608-4c87-8b16-0031f889f9b2

**Comment by aaaaargZombies** [comment]
https://github.com/geeksforsocialchange/gfsc-v3/assets/6824891/6cd8ef77-bced-4ae0-80a4-aeddde35e0ea
