### ISSUE TITLE
our work filter, can't switch between themes and work-type with keyboard

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/gfsc-v3#323]
can't seem to toggle filter types with keyboard, perhaps link should be a button.

https://github.com/geeksforsocialchange/gfsc-v3/assets/6824891/e56b668d-8d2e-4a59-9ce1-cbcce2278cad

**Comment by r-ferrier** [comment]
verified: works as it should

<img width="617" alt="Screenshot 2023-07-11 at 14 11 46" src="https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/81fdfd6a-6926-4872-bb95-d9199efc099b">
