### ISSUE TITLE
Add Resistance Lab Taser Report to portfolio

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/gfsc-v3#348]
This is our biggest flagship antiracism project and antiracism is first category alphebetically so feels bad to not have it!

## Acceptance criteria

- [x] Set to published
- [ ] Create images for index and gallery
- [ ] Add index image to repo
- [ ] Add gallery images and alt text to repo
- [ ] @geeksforsocialchange/content team to OK content

**Comment by kimadactyl** [comment]
adding to current milestone as its a publication and nearly done :)

**Comment by aaaaargZombies** [comment]
is @undividual assigned to this, are they writing the alt text?

**Comment by undividual** [comment]
I did not know I was! I'd maybe feel more comfortable if @honor-gfsc could do it, as I've not written alt text before and am not sure how much detail to go into. I am also not sure where to go to add it!

**Comment by r-ferrier** [comment]
I think it's a mistake from an old assignment! I'm happy to write some alt text. Kim just asked if we could toe it over the line yesterday

**Comment by undividual** [comment]
Great, please do — and when it's done, could you possibly show me where I can read it, just so I can get a sense of what our house style for alt text is?

**Comment by katjam** [comment]
Re. alt text, I like this from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt)
![image](https://github.com/geeksforsocialchange/gfsc-v3/assets/861172/1ac074f7-92e4-4fc6-8d33-0a069034a50f)

**Comment by kimadactyl** [comment]
> Re. alt text, I like this from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt) ![image](https://user-images.githubusercontent.com/861172/259780368-1ac074f7-92e4-4fc6-8d33-0a069034a50f.png)

nice, have added to the studio style guide
