### ISSUE TITLE
Category/Theme tags are updated on work pages

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/gfsc-v3#352]
## Description

Update the tags section on a work page to move it further down the page and add in a subtitle.

[design file here](https://www.figma.com/file/rLewb9kn4mUt8lLI0wuC7f/GFSC?type=design&node-id=404-862&mode=design&t=x9EwBz2Yk4uYge3r-0)

![Screenshot 2023-08-07 at 16 07 58](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/7ff5ff18-d29a-4af5-bbd9-ba72a00593cf)

## Acceptance criteria

- [ ] Tags appear under the main content of a work page
- [ ] Tags have a subtitle appended to them - `See more`

**Comment by kimadactyl** [comment]
Supercedes https://github.com/geeksforsocialchange/gfsc-v3/issues/334
