### ISSUE TITLE
CTA buttons can link to printable files

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/gfsc-v3#354]
## Description

\* Need to double check this is required before doing *

A button in the CTA section can also be used to view a printable plain text version of a publication

[design file here](https://www.figma.com/file/rLewb9kn4mUt8lLI0wuC7f/GFSC?type=design&node-id=404-862&mode=design&t=x9EwBz2Yk4uYge3r-0)

![Screenshot 2023-08-07 at 16 10 15](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/9e5a01e7-cdde-465a-b1a4-18d62d6f3397)

## Acceptance criteria

- [ ] I can add a button title, and a button type of `print` to a work markdown file and see it displayed in a CTA section on the website
- [ ] Clicking on a print button will open a print dialogue that contains just the main content of a publication formatted in a print friendly manner

**Comment by kimadactyl** [comment]
yeah i think this is overkill - we will have a properly nicely formatted PDF if people want something to print, if they want to read the text / use a screenreader we will have a html page for it. i did look into doing this before with pandoc but totally not worth the faff compared to just getting an actual designer to lay it out properly lol

i don't think there's a case we would list something here that doesnt already have a pdf made for it is what im saying

you can see more on the approach here tho if you're curious: https://plain-text.co/

**Comment by kimadactyl** [comment]
(so happy to close this as `wontfix` if you are too)

**Comment by r-ferrier** [comment]
Ok cool! Sounds good to me.
