### ISSUE TITLE
CTA buttons can link to downloadable files

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/gfsc-v3#355]
## Description

\* Need to double check this is required before doing *

A button in the CTA section can also be used to download a PDF publication

[design file here](https://www.figma.com/file/rLewb9kn4mUt8lLI0wuC7f/GFSC?type=design&node-id=404-862&mode=design&t=x9EwBz2Yk4uYge3r-0)

![Screenshot 2023-08-07 at 16 10 15](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/9e5a01e7-cdde-465a-b1a4-18d62d6f3397)

## Acceptance criteria

- [ ] I can add a button title, a file path, and a button type of `download` to a work markdown file and see it displayed in a CTA section on the website
- [ ] Clicking on a download button opens the download dialogue or begins downloading a file

**Comment by aaaaargZombies** [comment]
I'm not sure we automatically download the file, maybe it's better to let the browser do what it would normally do with a PDF and let people save it if they would like to?

**Comment by r-ferrier** [comment]
sorry yes, that's what I meant - just that whatever the browser usually does should then happen

**Comment by aaaaargZombies** [comment]
won't fix because we let the user view in browser and decide if they want to save
