### ISSUE TITLE
Add first posted / last updated paragraph styling shortcode for blog posts

### ISSUE THREAD

**Issue by jazzchatfield** [geeksforsocialchange/gfsc-v3#74]
## Acceptance criteria

- [x] I can see when a blog post was first published
- [ ] I can see when a blog post was last updated
- [x] last updated is in italics at top of blog post, under title
- [ ] No hardcoded last update content in markdown in blogs

## Plan

needs design proposal

- [ ] Make shortcode
- [ ] Add it in where necessary

**Comment by ivan-kocienski-gfsc** [comment]
So it looks like this is possible.

According to the [docs](https://gohugo.io/variables/page/#page-variables) we just need to add a section to the blog template like
```HTML
<time class="blog__meta blog__meta--date" datetime="{{ .Lastmod }}">
  {{ .Lastmod.Format "02 January 2006" }}
</time>
```

Unfortunately this is not automatic and we need to put in a `lastmod: 2023-10-15` field in every blog post by hand. Maybe it could be skipped if the field is not present.

**Comment by ivan-kocienski-gfsc** [comment]
Currently I have tucked this below the publish date and above the author photo. @undividual do you have any design thoughts on this?

![Screenshot_2023-06-28_14-49-23](https://github.com/geeksforsocialchange/gfsc-v3/assets/109223824/1e160779-1371-4ab0-93a9-07605f903bab)

**Comment by kimadactyl** [comment]
for me i would just put the last updated right at the end of the blog post as most of the time its the same date

**Comment by r-ferrier** [comment]
verified - I can see when a blog post was published & IF it was updated I can see when it was updated. Wasn't sure if we should show last updated as the published date if it doesn't exist? But I don't know that this is necessarily helpful info to repeat so think it is better without and will leave until raised.

![Screenshot 2023-07-06 at 10 31 12](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/26361c0e-6066-487d-a951-5d490933eaa2)

![Screenshot 2023-07-06 at 10 33 11](https://github.com/geeksforsocialchange/gfsc-v3/assets/46496391/3b239d11-42b1-452e-831e-91b20a397541)
