### ISSUE TITLE
Convert HTML to Hugo in 'placecal-capabilities-approach' blog post

### ISSUE THREAD

**Issue by jazzchatfield** [geeksforsocialchange/gfsc-v3#75]
As per Kims instruction this is actually about putting in the copy from the abstract and linking to the full paper

> This is really out of date anyway so when this is done it needs doing from the final submitted version whcih is prob hiding on my hard drive somewhere.
>
> For now maybe just put in the abstract and a link to the journal paper? 
> https://www.tandfonline.com/doi/full/10.1080/1369118X.2020.1767173
>
> I feel like it should support html tho somehow? Seems a huge ommission if there isn't some way to do it.

## Description
Extensive reformatting needs doing - so sticking this on backlog. Entire thing is in HTML which Hugo doesn't support

## Plan
- [ ] Step one to achieve this

**Comment by aaaaargZombies** [comment]
quick search suggests 46 closing rawhtml tags so I've added an extra `e` because I think it will take a very long time

**Comment by kimadactyl** [comment]
please check the comment about just deleting this and linking to the original article further up!

**Comment by ivan-kocienski-gfsc** [comment]
See the post on trans dimension launch for an example  of PDF link to
